plugin:
  has_options: false

  admin_tools:
    - name: laurent_school_admin_tool
      class: university

  widgets:
    - name: laurent_school_prof_menu_widget
      is_configurable: false

  tools:
    - name: laurent_school_prof_menu_tool
      class: info-circle
      is_displayable_in_workspace: false
      is_displayable_in_desktop: true